# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_Dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Dia')),
                ('FK_Hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Hora')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='horariocarrera',
            name='FK_Periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.Periodo'),
        ),
        migrations.AddField(
            model_name='horariocarrera',
            name='FK_Semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.Semestre'),
        ),
        migrations.AddField(
            model_name='clasehora',
            name='FK_HorarioCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.HorarioCarrera'),
        ),
        migrations.AddField(
            model_name='clasehora',
            name='FK_Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Materia'),
        ),
        migrations.AddField(
            model_name='clasehora',
            name='FK_Profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Profesor'),
        ),
        migrations.AddField(
            model_name='clasehora',
            name='FK_Salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.Salon'),
        ),
    ]
