# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariocarrera',
            old_name='Nombre',
            new_name='Clave',
        ),
    ]
