# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 03:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradoMaximo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('Serie', models.CharField(max_length=48)),
                ('HorasTeoricas', models.IntegerField()),
                ('HorasPracticas', models.IntegerField()),
                ('Creditos', models.IntegerField()),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(choices=[(b'Tiempo Completo: 22 horas (+/- 2)', b'Tiempo Completo: 22 horas (+/- 2)'), (b'1/2 Tiempo: 12 horas (+/- 2) ', b'1/2 Tiempo: 12 horas (+/- 2)'), (b'3/4 Tiempo: 16 horas (+/- 2)', b'3/4 Tiempo: 16 horas (+/- 2)'), (b'Asignatura: 19 horas max', b'Asignatura: 19 horas max')], max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('ApellidoPaterno', models.CharField(max_length=48)),
                ('ApellidoMaterno', models.CharField(max_length=48)),
                ('TelefonoCelular', models.IntegerField()),
                ('TelefonoCasa', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Tutorias', models.BooleanField()),
                ('NumeroEmpleado', models.CharField(blank=True, max_length=48, null=True)),
                ('Laboratorio', models.BooleanField()),
                ('Paquete', models.CharField(max_length=200)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_GradoMaximo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.GradoMaximo')),
                ('FK_NumeroHoras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escuela.NumeroHoras')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_Dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Dia')),
                ('FK_Hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Hora')),
                ('FK_Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
                ('FK_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Materia')),
                ('FK_Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=48)),
                ('FecAct', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='FK_Titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.Titulo'),
        ),
    ]
